version: '3.9'
services:
  order-management:
    container_name: order-management
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongodb:27017/order-management  # Local connection
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    restart: always
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js # Add mock products and categories
    restart: always
volumes:
  mongodata: